export { Login } from "./Login";
export { MyPage } from "./MyPage";
export { Storage } from "./MyPage";
export { List } from './List';
export { Design } from "./Design";
export { LoginPage } from "./LoginPage";
export { Register } from "./Register";
export { TradeMark } from "./TradeMark";
export { About } from "./About";
export { Community } from "./Community";
export { Write } from "./Write";
export { PostDetail } from "./PostDetail";
// export { main } from './main';
